# Generated by Django 2.1.1 on 2018-10-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.FloatField()),
                ('voltage_R', models.FloatField()),
                ('voltage_S', models.FloatField()),
                ('voltage_T', models.FloatField()),
                ('desbalance_U2', models.FloatField()),
                ('desbalance_U0', models.FloatField()),
                ('corriente_R', models.FloatField()),
                ('corriente_S', models.FloatField()),
                ('corriente_T', models.FloatField()),
                ('corriente_N', models.FloatField()),
                ('desbalance_I2', models.FloatField()),
                ('desbalance_I0', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Adquisiciones',
            },
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pot_aparente', models.FloatField()),
                ('Pot_activaVr', models.FloatField()),
                ('Pot_activaVs', models.FloatField()),
                ('Pot_activaVt', models.FloatField()),
                ('Pot_reactivaVr', models.FloatField()),
                ('Pot_reactivaVs', models.FloatField()),
                ('Pot_reactivaVt', models.FloatField()),
                ('Pot_distoVr', models.FloatField()),
                ('Pot_distoVs', models.FloatField()),
                ('Pot_distoVt', models.FloatField()),
                ('FP_r', models.FloatField()),
                ('FP_s', models.FloatField()),
                ('THD_Vr', models.FloatField()),
                ('THD_Vs', models.FloatField()),
                ('THD_Vt', models.FloatField()),
                ('THD_Ir', models.FloatField()),
                ('THD_Is', models.FloatField()),
                ('THD_It', models.FloatField()),
                ('Phi_r', models.FloatField()),
                ('Phi_s', models.FloatField()),
                ('Phi_t', models.FloatField()),
                ('CosPhi_r', models.FloatField()),
                ('CosPhi_s', models.FloatField()),
                ('CosPhi_t', models.FloatField()),
                ('Espectro_Vr', models.TextField()),
                ('Espectro_Vs', models.TextField()),
                ('Espectro_Vt', models.TextField()),
                ('Espectro_Ir', models.TextField()),
                ('Espectro_Is', models.TextField()),
                ('Espectro_It', models.TextField()),
                ('Espectro_In', models.TextField()),
                ('frecuencia', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Calidad de Energia',
            },
        ),
        migrations.CreateModel(
            name='dips_swells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmin', models.FloatField()),
                ('vmax', models.FloatField()),
                ('duracion', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Caida y sobrelevacion',
            },
        ),
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('iconoimg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='img_son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termico', models.ImageField(upload_to='termica')),
                ('sonido', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Imagen term y sonido',
            },
        ),
        migrations.CreateModel(
            name='interrupcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Interrupciones',
            },
        ),
        migrations.CreateModel(
            name='rvc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Cambios rapidos Tension',
            },
        ),
        migrations.CreateModel(
            name='SET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Transformadores',
            },
        ),
        migrations.AddField(
            model_name='rvc',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
        migrations.AddField(
            model_name='interrupcion',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
        migrations.AddField(
            model_name='img_son',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
        migrations.AddField(
            model_name='dips_swells',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
        migrations.AddField(
            model_name='calidad',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
        migrations.AddField(
            model_name='adquisicion',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSetV1.SET'),
        ),
    ]
